### ISSUE TITLE
ability to customise handlers via options?

### ISSUE THREAD

**Issue by xiaoxinghu** [syntax-tree/hast-util-to-estree#1]
### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 

### Subject

I would like to be able to customize (replacing existing and/or adding more) handlers via options.

### Problem

I tried to use this module to parse my `hast` to `estree`, but I have something extra in my hast (via `raw` nodes) I would like to be able to deal with myself. It's easy to copy & paste code here into my project, but it'd be good to be able to leverage this module instead.

### Solution

add `handlers` option in `options` and merge it with the default one.

### Alternatives

Can't think of any good ones.

**Comment by wooorm** [comment]
Sounds good to me! Something like [`mdast-util-to-hast`’s handlers](https://github.com/syntax-tree/mdast-util-to-hast)? Can you work on a PR?

**Comment by xiaoxinghu** [comment]
Sure, on it.

**Comment by wooorm** [comment]
Closed in https://github.com/syntax-tree/hast-util-to-estree/pull/3, and released!
