### ISSUE TITLE
missing the type definition file in package

### ISSUE THREAD

**Issue by xiaoxinghu** [syntax-tree/hast-util-to-estree#9]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

2.3.2

### Steps to reproduce

Install the package.

### Expected behavior

The package should contain `index.d.ts` file as described in README and package.json file. Was the build command skipped before releasing the package?

### Actual behavior

`index.d.ts` file is missing.

### Affected runtime and version

any

**Comment by wooorm** [comment]
Thanks! https://github.com/syntax-tree/hast-util-to-estree/releases/tag/2.3.3
